### ISSUE TITLE
A Livewire component was not found

### ISSUE THREAD

**Issue by sourabhsurana1008** [designatedcoder/coders_filament_admin_panel#5]
Detail link - https://flareapp.io/share/x5Mo14XP#F67

Livewire \ Exceptions\ ComponentNotFoundException
PHP 8.1.11
9.36.3
Unable to find component: [app.filament.resources.role-resource.relation-managers.permissions-relation-manager]

$response = \Livewire\Livewire::mount(\Livewire\Livewire::getAlias($manager, $manager::getName()), ['ownerRecord' => $ownerRecord, 'pageClass' => $pageClass]);

**Comment by designatedcoder** [comment]
This looks like less of an issue with the code and more of an issue with the implementation.  I suggest looking over the code again to make sure the role resource and permission relation manager are included to get rid of this error.  Hope this helps and good luck to you.
